server:
  port: 8077

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: WA Task monitor
  main:
    allow-bean-definition-overriding: true

camunda:
  url: ${CAMUNDA_URL:http://camunda-local-bpm/engine-rest}

task.configuration.service:
  url: ${TASK_CONFIGURATION_SERVICE_URL:http://localhost:8091}

task.configurator.scheduling:
  fixedRate: 60000

idam:
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_TASK_MONITOR:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME_TASK_MONITOR:wa_task_monitor}

