server:
  port: 8077

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/wa/"
  jackson.serialization.INDENT_OUTPUT: true
  application:
    name: WA Task monitor
  main:
    allow-bean-definition-overriding: true
  freemarker:
    check-template-location: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OPEN_ID_IDAM_URL:http://sidam-api}/o/jwks
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_IDAM_URL:http://sidam-api}/o
        registration:
          oidc:
            client-id: ${WA_IDAM_CLIENT_ID:wa}
            client-secret: ${WA_IDAM_CLIENT_SECRET:something}

camunda:
  url: ${CAMUNDA_URL:http://camunda-local-bpm/engine-rest}

task-management:
  url: ${TASK_MANAGEMENT_SERVICE_URL:http://localhost:8087}

case-event-handler.service.url: ${CASE_EVENT_HANDLER_SERVICE_URL:http://localhost:8088}

ia_case.service.url: ${IA_CASE_SERVICE_URL:http://localhost:8090}

core_case_data:
  api:
    search.url: ${CCD_SEARCH_URL:http://wiremock}
    url: ${CCD_URL:http://ccd-data-store-api}

idam:
  url: ${OPEN_ID_IDAM_URL:http://sidam-api}
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_TASK_MONITOR:AAAAAAAAAAAAAAAA}
    name: wa_task_monitor
  s2s-authorised:
    services: ${WA_S2S_AUTHORIZED_SERVICES:wa_task_monitor,wa_task_management_api}
  system:
    username: ${WA_SYSTEM_USERNAME:some_user@hmcts.net}
    password: ${WA_SYSTEM_PASSWORD:password}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://xui-webapp/oauth2/callback}
  scope: "openid profile roles"
  api:
    baseUrl: ${IDAM_URL:http://sidam-api}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/loggers/**"
    - "/swagger-resources/**"
    - "/swagger-ui/**"
    - "/swagger-ui/index.html"
    - "/v3/**"
    - "/favicon.ico"

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: basic


job:
  configuration:
    camunda-max-results: ${CONFIGURATION_CAMUNDA_MAX_RESULTS:100}
    camunda-time-limit-flag: ${CONFIGURATION_TIME_LIMIT_FLAG:true}
    #number of minutes
    camunda-time-limit: ${CONFIGURATION_TIME_LIMIT:60}
  initiation:
    camunda-max-results: ${INITIATION_CAMUNDA_MAX_RESULTS:100}
    camunda-time-limit-flag: ${INITIATION_TIME_LIMIT_FLAG:true}
    #number of minutes
    camunda-time-limit: ${INITIATION_TIME_LIMIT:1}
  termination:
    camunda-max-results: ${TERMINATION_CAMUNDA_MAX_RESULTS:100}
    camunda-time-limit-flag: ${TERMINATION_TIME_LIMIT_FLAG:true}
    #number of minutes
    camunda-time-limit: ${TERMINATION_TIME_LIMIT:1}

role-assignment-service:
  url: ${ROLE_ASSIGNMENT_URL:http://role-assignment}
