server:
  port: 8077

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

camunda:
  url: ${CAMUNDA_URL:http://camunda-bpm/engine-rest}

spring:
  application:
    name: WA Task monitor
