java:
  applicationPort: 8077
  image: 'hmctspublic.azurecr.io/wa/task-monitor:latest'
  ingressHost: wa-task-monitor-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: wa
  environment:
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CAMUNDA_URL: "http://camunda-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/engine-rest"
    TASK_MANAGEMENT_SERVICE_URL: "http://wa-task-management-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CASE_EVENT_HANDLER_SERVICE_URL: "http://wa-case-event-handler-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_SEARCH_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    ROLE_ASSIGNMENT_URL: "http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CONFIGURATION_CAMUNDA_MAX_RESULTS: 100
    CONFIGURATION_TIME_LIMIT_FLAG: true
    CONFIGURATION_TIME_LIMIT: 60

    INITIATION_CAMUNDA_MAX_RESULTS: 100
    INITIATION_TIME_LIMIT_FLAG: true
    INITIATION_TIME_LIMIT: 120

    TERMINATION_CAMUNDA_MAX_RESULTS: 100
    TERMINATION_TIME_LIMIT_FLAG: true
    TERMINATION_TIME_LIMIT: 120

  keyVaults:
    wa:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: s2s-secret-task-monitor
          alias: S2S_SECRET_TASK_MONITOR
        - name: wa-system-username
          alias: WA_SYSTEM_USERNAME
        - name: wa-system-password
          alias: WA_SYSTEM_PASSWORD
        - name: wa-idam-client-secret
          alias: WA_IDAM_CLIENT_SECRET
